Druzhinin Arseny HW BasketBall
otopba/basketball_homework pull request #8
Opened 2019-04-11 18:04 UTC by senyast4745

2019-04-20 11:41 UTC, otopba requested changes
Круто! Интересное решение!

Комментарии по ui:
- когда меняешь сложность слово “reset” двигается;
- не понятно что делает кнопка reset;
- при переходе на экран statistics почему-то сдвигается фон;
- когда забивается гол, не сразу увеличивается счет, а только после того, как мяч остановится; 
- у мяча прозрачные линии.

Ресурсы сделаны неверно. Должны быть нарезаны по разрешениям и размещены в соответствующих папках

2019-04-20 11:41 UTC, otopba commented on app/build.gradle
> +    implementation 'org.jetbrains:annotations-java5:15.0'
Зачем? У суппорта есть встроенные аннотации

`import android.support.annotation.Nullable;`

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/AccuracyResource.java
> +    private static List<Double> accuracy = new ArrayList<>();;
Лишняя точка-запятая

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/AccuracyView.java
> +import java.net.PasswordAuthentication;
Зачем?

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/AccuracyView.java
> +    private final Paint goodPaint = new Paint(Paint.ANTI_ALIAS_FLAG);
good paint? =)

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/AccuracyResource.java
> +class AccuracyResource {
Лучше не делать такой статичный ресурс. А создавать один раз и передавать его места где это требуется.
Либо использовать паттерн синглтон

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/AccuracyView.java
> +            originalData = new ArrayList<>();
Лучше не создавать ничего. Заранее сделай лист

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/AccuracyView.java
> +        int measuredHeight = getMeasuredHeight() - paddingTop - getPaddingBottom();
В onDraw луче использовать не `getMeasuredHeight` а `getHeight` и для ширины также

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/BackPressListener.java
> +    public void onBackPressed();
Публичные интерфейсы по-умолчанию имеют все методы public

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/GameFragment.java
> +    boolean isVibrationOn = true;
Переменные лучше называть без is то есть `vibrationOn`. А если будет например геттер, то он уже будет иметь имя `isVibrationOn()`

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/GameFragment.java
> +    ValueAnimator animator;
Тут осознанно сделана видимость package?

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/GameFragment.java
> +    public void onCreate(@Nullable Bundle savedInstanceState) {
В `onCreate`:
Нужно в случае если `savedInstanceState == null`, то брать данные из аргументов. Если `savedInstanceState != null`, то брать данные из `savedInstanceState`.

В `onResume`:
Тут ничего не нужно читать из аргументов и писать в аргументы

В `onSaveInstanceState`:
Нужно сохранять данные, которые могут быть считаны в `onCreate`

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/GameFragment.java
> +            scoreView.setText(Integer.toString(score));
Лучше указать английскую локаль, чем делать аннотацию

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/GameFragment.java
> +                /*if(animator != null){
?

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/GameFragment.java
> +            scoreView.setText(Integer.toString(score));
Такие вложенные вещи лучше выносить в отдельные методы. Когда несколько раз подряд создаются какие-то анонимные классы, тяжело читать код

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/GameFragment.java
> +
Лишние строки

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/GameFragment.java
> +                    {
Очень странное написание логов. Зачем тут скобки?

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/GameFragment.java
> +     /*                   if (Math.sqrt(Math.pow(ballView.getX() - leftSideHoopLocation[0], 2)
?

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/GameFragment.java
> +                                && ballView.getX() + ballView.getWidth() <= rightSideHoopLocation[0]
А что за волшебные числа? 20 10 50 ?

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/GameFragment.java
> +                            scoreView.setText(Integer.toString(score));
Локаль

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/GameFragment.java
> +
лишняя строка

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/GameFragment.java
> +public class GameFragment extends Fragment {
Лучше сохранять все аниматоры и останавливать их при уничтожении фрагмента

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/LinearInterpolation.java
> +        int jPrevious = 0;
jPrevious?

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/MainActivity.java
> +    int width;
Тут у половины полей нет указания видимости

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/MainActivity.java
> +    private String LOG_TAG = "Main_Activity_logs";
Часто делают так:
private static final String TAG = MainActivity.class.getName();

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/MainActivity.java
> +        mediaPlayer = MediaPlayer.create(getApplicationContext(), R.raw.backgroud_main_music);
Не нужно делать статик. Нужно создавать и останавливать когда нужно

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/MainActivity.java
> +                Log.d(LOG_TAG, "play callback");
Тут тоже стоит выносить это, разделяй длинные сложные методы на более маленькие и простые

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/MainActivity.java
> +
Строка

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/MenuFragment.java
> +    OnMenuListener onMenuListener;
Видимость

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/MenuFragment.java
> +        if(getActivity() != null)
Скобки

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/SettingsFragment.java
> +    OnCloseSetListener closeListener;
Видимость

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/SettingsFragment.java
> +        Log.d(LOG_TAG, "onCreate args " + Boolean.toString(vibrate));
Можно без `toString`

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/SettingsFragment.java
> +                case MotionEvent.ACTION_UP:
Зачем тут `ACTION_UP`?

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/SettingsFragment.java
> +    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
Тут тоже дели на более маленькие методы

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/WinFragment.java
> +    MediaPlayer mediaPlayer;
Видимость

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/WinFragment.java
> +        final ImageView view1 = view.findViewById(R.id.fragment_goal_whistle);
view1?

2019-04-20 11:41 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/WinFragment.java
> +    MediaPlayer mediaPlayer;
Нужно освобождать плеер при остановке фрагмента

2019-04-20 11:41 UTC, otopba commented on app/src/main/res/drawable/stat_fragment_text_shape.xml
> +<?xml version="1.0" encoding="utf-8"?>
Не используется

2019-04-20 11:41 UTC, otopba commented on app/src/main/res/layout/fragment_game.xml
> +
Куча лишних строк

2019-04-20 11:41 UTC, otopba commented on app/src/main/res/layout/fragment_game.xml
> +            android:contentDescription="@string/hoop" />
Нет такой строки

2019-04-20 11:41 UTC, otopba commented on app/src/main/res/layout/fragment_menu.xml
> +
Лишние строки

2019-04-23 15:40 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/basketball/AccuracyView.java
> +    private final Paint goodPaint = new Paint(Paint.ANTI_ALIAS_FLAG);
Это для отрисовки зелёным цветом поппданий

2019-04-23 15:41 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/basketball/AccuracyView.java
> +            originalData = new ArrayList<>();
Это ты о каком из косяков?)

2019-04-23 16:30 UTC, senyast4745 commented on app/src/main/res/layout/fragment_menu.xml
> +
Done

2019-04-23 16:31 UTC, senyast4745 commented on app/src/main/res/layout/fragment_game.xml
> +            android:contentDescription="@string/hoop" />
Done

2019-04-23 16:31 UTC, senyast4745 commented on app/src/main/res/layout/fragment_game.xml
> +
Done

2019-04-23 16:31 UTC, senyast4745 commented on app/src/main/res/drawable/stat_fragment_text_shape.xml
> +<?xml version="1.0" encoding="utf-8"?>
Done

2019-04-23 16:31 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/basketball/WinFragment.java
> +    MediaPlayer mediaPlayer;
Done

2019-04-23 16:31 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/basketball/AccuracyResource.java
> +class AccuracyResource {
Done

2019-04-23 16:31 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/basketball/AccuracyView.java
> +import java.net.PasswordAuthentication;
Done

2019-04-23 16:31 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/basketball/AccuracyResource.java
> +    private static List<Double> accuracy = new ArrayList<>();;
Done

2019-04-28 19:37 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/basketball/GameFragment.java
> +
Done

2019-04-28 19:37 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/basketball/GameFragment.java
> +
Done

2019-04-28 19:37 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/basketball/LinearInterpolation.java
> +        int jPrevious = 0;
Done

2019-04-28 19:37 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/basketball/MainActivity.java
> +    int width;
Done

2019-04-28 19:38 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/basketball/MainActivity.java
> +        mediaPlayer = MediaPlayer.create(getApplicationContext(), R.raw.backgroud_main_music);
Я хотел чтобы при смене фрагментов музыка шла непрерывно, но из фрагмента настроек её можно было остановить

2019-04-28 19:39 UTC, senyast4745 commented on app/src/main/java/ru/ok/technopolis/basketball/MainActivity.java
> +
Done

2019-04-29 21:04 UTC, otopba commented on app/src/main/java/ru/ok/technopolis/basketball/AccuracyView.java
>  import org.jetbrains.annotations.Nullable;
Лучше использовать `android.support.annotation.Nullable`

2019-04-29 21:05 UTC, otopba commented
Не все комментарии поправлены. Но работа все равно хорошая.

2019-04-29 21:05 UTC, otopba commented
Работа принята
10 балов

2020-05-19 21:36 UTC, closed without merging